# Generated by Django 2.2.5 on 2019-09-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo del Ticket')),
                ('content', models.TextField(max_length=1000, verbose_name='Contenido del Ticket')),
                ('created', models.DateTimeField(verbose_name='Momento en el que fue Creado')),
                ('status', models.IntegerField(choices=[(1, 'Abierto'), (2, 'En Proceso'), (3, 'Cerrado'), (4, 'Re-Abierto'), (5, 'Esperando por Información')], verbose_name='Estatus del Ticket')),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], verbose_name='Prioridad del Ticket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador del Ticket')),
            ],
        ),
    ]
