# Generated by Django 2.2.5 on 2019-09-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpgo_app', '0002_department_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id_management',
            new_name='management',
        ),
    ]
