# Generated by Django 2.2.5 on 2019-09-04 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpgo_app', '0003_auto_20190903_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Rango en el Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha de la Acción')),
                ('claimed', models.BooleanField(default=False, null=True, verbose_name='¿Reclamado?')),
                ('assigned', models.BooleanField(default=False, null=True, verbose_name='¿Asignado?')),
                ('closed', models.BooleanField(default=False, null=True, verbose_name='¿Cerrado?')),
                ('re_opened', models.BooleanField(default=False, null=True, verbose_name='¿Re-Abierto?')),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza la Acción')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpgo_app.Ticket', verbose_name='Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=250, null=True, verbose_name='Imagen del Perfil')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpgo_app.Department', verbose_name='Departamento al que Pertenece')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpgo_app.Job_Titles', verbose_name='Cargo dentro de la Organización')),
                ('rank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simpgo_app.Rank', verbose_name='Rango en el Sistema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
