# Generated by Django 2.2.5 on 2019-09-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpgo_app', '0004_job_titles_profile_rank_ticket_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Imagen del Perfil'),
        ),
    ]
